name: datachat-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - streamlit
  - altair=5.5.0
  - pyarrow
  - sqlalchemy
  - jinja2
  - pydantic
  - requests
  - click
  - gitpython
  - pip:
      - google-genai
      - google-generativeai
      - langchain
      - matplotlib
      - tqdm
      - google-api-python-client